# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dragons Eat Everything
email: lelefuchur@posteo.de
description: > # this means to ignore newlines until "baseurl:"
  Dragons Eat Everything is the home of All You Can Eat, the Ninja Pirate Radio
  from Space and so much more!
baseurl: "/DragonsEatEverything" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site
twitter_username:
github_username:  LeleFuchur

# Build settings
markdown: kramdown
